# Generated by Django 5.1.3 on 2024-11-16 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
