# Generated by Django 5.1.3 on 2024-11-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
