# Generated by Django 5.1.3 on 2024-11-24 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0006_remove_card_image_remove_cube_cube_image_cardimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='card_list',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='player_list',
        ),
    ]
