# Generated by Django 5.1.3 on 2024-11-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0007_remove_draft_card_list_remove_draft_player_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
