# Generated by Django 6.0.1 on 2026-01-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0009_alter_draft_player_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
