# Generated by Django 6.0.1 on 2026-01-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0010_draft_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='current_pack',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draft',
            name='current_pick',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='draftplayer',
            name='seat_position',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DraftPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_number', models.IntegerField()),
                ('cards', models.ManyToManyField(related_name='in_draft_packs', to='drafting.card')),
                ('current_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_packs', to='drafting.draftplayer')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='drafting.draft')),
                ('original_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_packs', to='drafting.draftplayer')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_number', models.IntegerField()),
                ('pick_number', models.IntegerField()),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='drafting.card')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='drafting.draft')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='drafting.draftplayer')),
            ],
            options={
                'unique_together': {('draft', 'player', 'card')},
            },
        ),
    ]
