import { Permanent } from '@/types';

/**
 * bundleKey returns a stable string identifying a permanent's "visual & state
 * identity" for the purpose of bundling identical permanents into one tile.
 * Two permanents bundle together iff bundleKey(a) === bundleKey(b).
 *
 * The key intentionally excludes per-instance noise (instance_id, original
 * draw order) and includes every gameplay-relevant state field. When state
 * diverges (e.g., one becomes tapped, takes damage, gains a counter), the
 * keys diverge and the bundle splits automatically.
 *
 * Phase 1 limitation: aura/equipment attachments aren't reflected here —
 * those live on the attacker/aura permanent, not on the recipient. If two
 * creatures only differ by an attached Pacifism, they'll currently bundle.
 * Revisit if it matters in practice.
 */
export function bundleKey(p: Permanent): string {
  const counters = sortedRecord(p.counters);
  const protection = [...(p.protection ?? [])].sort();
  const roles = (p.attachedRoles ?? []).map(r => r.type).sort();

  // Tokens generated by applyCreateToken have a random card_id per instance
  // (see engine/effects/battlefield.ts), so card_id alone can't identify them
  // as "the same kind of permanent." Derive a stable identity from the printed
  // characteristics instead. Real DB-backed cards still key off card_id.
  const isToken =
    !!p.is_token ||
    !!(p as any).isToken ||
    typeof p.card_id === 'string';
  const identity = isToken
    ? `tok:${p.name}|${p.type_line ?? ''}|${p.power ?? ''}/${p.toughness ?? ''}|${[...(p.colors ?? [])].sort().join('')}|${[...(p.keywords ?? [])].sort().join(',')}`
    : `card:${p.card_id}`;

  return JSON.stringify({
    identity,
    is_token: isToken,
    tapped: !!p.tapped,
    summoning_sick: !!p.summoning_sick,
    counters,
    damage: p.damage ?? 0,
    buffPower: p.buffPower ?? 0,
    buffToughness: p.buffToughness ?? 0,
    prowessBonus: p.prowessBonus ?? 0,
    attacking: !!p.attacking,
    attackTarget: p.attackTarget ?? '',
    blocking: !!p.blocking,
    protection,
    protUEOT: !!p.protection_until_end_of_turn,
    loyalty: p.loyalty ?? null,
    pwActivated: !!p._loyaltyActivatedThisTurn,
    dashed: !!(p as any)._dashed,
    deathtouched: !!p.damaged_by_deathtouch,
    roles,
    equippedTo: p.equippedTo?.instance_id ?? '',
    attachedTo: p.attachedTo?.instance_id ?? '',
  });
}

function sortedRecord(rec?: Record<string, number>): Record<string, number> {
  if (!rec) return {};
  const out: Record<string, number> = {};
  for (const k of Object.keys(rec).sort()) {
    if (rec[k]) out[k] = rec[k];
  }
  return out;
}

export interface Bundle {
  key: string;
  permanents: Permanent[];
}

/**
 * Group permanents by bundleKey. Preserves insertion order: each bundle's
 * permanents array is in original order (so index 0 is the oldest instance,
 * which Phase 1 uses as the representative for single-click actions).
 */
export function groupByBundleKey(permanents: Permanent[]): Bundle[] {
  const groups = new Map<string, Permanent[]>();
  const order: string[] = [];
  for (const p of permanents) {
    const k = bundleKey(p);
    if (!groups.has(k)) {
      groups.set(k, []);
      order.push(k);
    }
    groups.get(k)!.push(p);
  }
  return order.map(k => ({ key: k, permanents: groups.get(k)! }));
}
