# Generated by Django 6.0.1 on 2026-02-12 06:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('scryfall_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('mana_cost', models.CharField(blank=True, default='', max_length=50)),
                ('cmc', models.IntegerField(default=0, help_text='Converted Mana Cost', validators=[django.core.validators.MinValueValidator(0)])),
                ('type_line', models.CharField(db_index=True, default='', max_length=255)),
                ('oracle_text', models.TextField(blank=True, default='')),
                ('colors', models.CharField(blank=True, db_index=True, default='', help_text='WUBRG color identity', max_length=5)),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('card_data', models.JSONField(blank=True, default=dict, help_text='Game mechanics: abilities, keywords, special effects (edit manually)')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic Rare')], db_index=True, default='common', max_length=20)),
                ('set_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='cards_card_name_a125cc_idx'), models.Index(fields=['colors'], name='cards_card_colors_62e89d_idx'), models.Index(fields=['cmc'], name='cards_card_cmc_ce54e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('image_type', models.CharField(choices=[('small', 'Small'), ('normal', 'Normal'), ('large', 'Large'), ('png', 'PNG'), ('art_crop', 'Art Crop')], default='normal', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.card')),
            ],
            options={
                'unique_together': {('card', 'image_type')},
            },
        ),
    ]
