# Generated by Django 6.0.1 on 2026-02-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type_line', models.CharField(default='Token', max_length=255)),
                ('colors', models.CharField(blank=True, default='', help_text='WUBRG color identity', max_length=5)),
                ('power', models.CharField(blank=True, max_length=10, null=True)),
                ('toughness', models.CharField(blank=True, max_length=10, null=True)),
                ('token_data', models.JSONField(blank=True, default=dict, help_text='Abilities and keywords for this token')),
                ('created_by', models.TextField(blank=True, default='', help_text='Which cards create this token (for reference)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
