# Generated by Django 6.0.1 on 2026-02-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_token'),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlestate',
            name='required_cards',
            field=models.ManyToManyField(blank=True, help_text='Cards referenced in this puzzle state', related_name='used_in_puzzles', to='cards.card'),
        ),
        migrations.AddField(
            model_name='puzzlestate',
            name='required_tokens',
            field=models.ManyToManyField(blank=True, help_text='Tokens referenced in this puzzle state', related_name='used_in_puzzles', to='cards.token'),
        ),
    ]
